### ISSUE TITLE
Very big APPLY button for applying new color style

### ISSUE THREAD

**Issue by hinell** [puranjayjain/chrome-color-picker#4]
Feature, of course.
Just to avoid picking up my new color by each time pressing ctrl+c and ctrl+p buttons :neutral_face:  
Thanks alot.

**Comment by puranjayjain** [comment]
@hinell can you explain it in a bit detail, I didn't get you completely 😕

**Comment by hinell** [comment]
@puranjayjain 
Just need button like this ("apply" or whatever you like or prefer, dsnt matter): 
![screenshot_1](https://cloud.githubusercontent.com/assets/8136158/14763529/c035ccd8-09a0-11e6-91db-87ad8bed5044.png)
that will do the same as the "enter" button pressing do while the picker is opened up. 

Here some styles, that is used in preview above, if you need 

``` css
.ccp-panel .apply-button {
    display: flex;
    text-align: center;
    justify-content: center;
    background: #2C313A;
    color: white;
    padding: 0;
    min-width: 100%;
    font-size: 1.5em;
    min-height: 1em;
    border: 1px solid #181a1f;
    border-radius: 4px;
    font-weight: bold;
    letter-spacing: .2em;
}
```
